In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('bookbuy/spiders\csvdatabookbuy.csv')

<>:1: SyntaxWarning: invalid escape sequence '\c'
<>:1: SyntaxWarning: invalid escape sequence '\c'
C:\Users\This PC\AppData\Local\Temp\ipykernel_3188\2391532853.py:1: SyntaxWarning: invalid escape sequence '\c'
  df=pd.read_csv('bookbuy/spiders\csvdatabookbuy.csv')

In [4]:
df

,Author,Book_name,Content,Issuiers,Market_Price,Num_Page,Price,Publish_date,Publisher,Status,Weight
0,Lyle & Michael,Giáng Sinh Ở Thành Phố Ma Thuật - Tập 3: Âm Mư...,là tập 3 của bộ truyện tranh Giáng sinh ở thàn...,Văn Việt,90000,210,72000,12/07/2016,NXB Văn Học,Còn hàng,310
1,Oprah Winfrey,Những Điều Tôi Biết Chắc (Tái Bản 2018),Lắm lúc một câu trả lời chẳng phải dễ kiếm ra....,Alphabooks,99000,232,84000,12/01/2018,NXB Thế Giới,Hết hàng,450
2,George Macdonald,Sau Lưng Gió Bấc,"Nếu bạn năm tuổi, bạn sẽ thấy đây là một cuốn ...",Nhã Nam,90000,420,76500,13/07/2016,NXB Hội Nhà Văn,Hết hàng,650
3,Fiona MacDonald,Sẽ Ra Sao Nếu Thiếu Nhà Vệ Sinh,"Bạn sẽ "" giải quyết nỗi buồn"" thế nào nếu khôn...",NXB Kim Đồng,22000,Đang,18500,11/07/2016,NXB Kim Đồng,Hết hàng,200
4,Amanda Huynh,Lam,Nhân vật chính của các mẩu truyện hay tản văn ...,NXB Trẻ,85000,164,72000,14/07/2016,NXB Trẻ,Hết hàng,300
...,...,...,...,...,...,...,...,...,...,...,...
1267,Kudoh Noriko,Chiếp Chiếp Đi Công Viên Giải Trí,chiếp chiếp.,Nhã Nam,44000,32,37000,22/09/2017,NXB Thế Giới,Hết hàng,200
1268,Trường An,Hồ Dương - Tâp 1,"Trong những năm tháng đó, ai đúng ai sai khôn...",NXB Phụ Nữ,217000,728,184000,01/09/2017,NXB Phụ Nữ,Hết hàng,950
1269,Karen Dillon,HBR Guide To - Sống Sót Nơi Công Sở,• Chống lại những kẻ đâm sau lưng và ưa bắt nạt ;,Alphabooks,99000,228,84000,22/09/2017,NXB Thế Giới,Hết hàng,370
1270,Porter Erisman,Thế Giới Alibaba Của Jack Ma,Tác giả viết sách còn làm một bộ phim tài liệu...,NXB Trẻ,105000,322,89000,01/09/2017,NXB Trẻ,Hết hàng,522
1271,Lê Anh Vinh,Học Toán Qua Truyện Cổ Tích - Cây Khế,là sản phẩm nằm trong bộ sản phẩm Học toán qua...,Thái Hà,49000,34,41500,10/10/2017,NXB Thế Giới,Hết hàng,184

In [5]:
df.isna().any()

Author           True
Book_name       False
Content          True
Issuiers        False
Market_Price    False
Num_Page        False
Price           False
Publish_date    False
Publisher       False
Status          False
Weight          False
dtype: bool

In [6]:
df.reset_index(inplace=True)

In [7]:
df

,index,Author,Book_name,Content,Issuiers,Market_Price,Num_Page,Price,Publish_date,Publisher,Status,Weight
0,0,Lyle & Michael,Giáng Sinh Ở Thành Phố Ma Thuật - Tập 3: Âm Mư...,là tập 3 của bộ truyện tranh Giáng sinh ở thàn...,Văn Việt,90000,210,72000,12/07/2016,NXB Văn Học,Còn hàng,310
1,1,Oprah Winfrey,Những Điều Tôi Biết Chắc (Tái Bản 2018),Lắm lúc một câu trả lời chẳng phải dễ kiếm ra....,Alphabooks,99000,232,84000,12/01/2018,NXB Thế Giới,Hết hàng,450
2,2,George Macdonald,Sau Lưng Gió Bấc,"Nếu bạn năm tuổi, bạn sẽ thấy đây là một cuốn ...",Nhã Nam,90000,420,76500,13/07/2016,NXB Hội Nhà Văn,Hết hàng,650
3,3,Fiona MacDonald,Sẽ Ra Sao Nếu Thiếu Nhà Vệ Sinh,"Bạn sẽ "" giải quyết nỗi buồn"" thế nào nếu khôn...",NXB Kim Đồng,22000,Đang,18500,11/07/2016,NXB Kim Đồng,Hết hàng,200
4,4,Amanda Huynh,Lam,Nhân vật chính của các mẩu truyện hay tản văn ...,NXB Trẻ,85000,164,72000,14/07/2016,NXB Trẻ,Hết hàng,300
...,...,...,...,...,...,...,...,...,...,...,...,...
1267,1267,Kudoh Noriko,Chiếp Chiếp Đi Công Viên Giải Trí,chiếp chiếp.,Nhã Nam,44000,32,37000,22/09/2017,NXB Thế Giới,Hết hàng,200
1268,1268,Trường An,Hồ Dương - Tâp 1,"Trong những năm tháng đó, ai đúng ai sai khôn...",NXB Phụ Nữ,217000,728,184000,01/09/2017,NXB Phụ Nữ,Hết hàng,950
1269,1269,Karen Dillon,HBR Guide To - Sống Sót Nơi Công Sở,• Chống lại những kẻ đâm sau lưng và ưa bắt nạt ;,Alphabooks,99000,228,84000,22/09/2017,NXB Thế Giới,Hết hàng,370
1270,1270,Porter Erisman,Thế Giới Alibaba Của Jack Ma,Tác giả viết sách còn làm một bộ phim tài liệu...,NXB Trẻ,105000,322,89000,01/09/2017,NXB Trẻ,Hết hàng,522
1271,1271,Lê Anh Vinh,Học Toán Qua Truyện Cổ Tích - Cây Khế,là sản phẩm nằm trong bộ sản phẩm Học toán qua...,Thái Hà,49000,34,41500,10/10/2017,NXB Thế Giới,Hết hàng,184

In [8]:
df['Status'] = df['Status'].apply(lambda x: 0 if x == 'Hết hàng' else 1)

In [9]:
df

,index,Author,Book_name,Content,Issuiers,Market_Price,Num_Page,Price,Publish_date,Publisher,Status,Weight
0,0,Lyle & Michael,Giáng Sinh Ở Thành Phố Ma Thuật - Tập 3: Âm Mư...,là tập 3 của bộ truyện tranh Giáng sinh ở thàn...,Văn Việt,90000,210,72000,12/07/2016,NXB Văn Học,1,310
1,1,Oprah Winfrey,Những Điều Tôi Biết Chắc (Tái Bản 2018),Lắm lúc một câu trả lời chẳng phải dễ kiếm ra....,Alphabooks,99000,232,84000,12/01/2018,NXB Thế Giới,0,450
2,2,George Macdonald,Sau Lưng Gió Bấc,"Nếu bạn năm tuổi, bạn sẽ thấy đây là một cuốn ...",Nhã Nam,90000,420,76500,13/07/2016,NXB Hội Nhà Văn,0,650
3,3,Fiona MacDonald,Sẽ Ra Sao Nếu Thiếu Nhà Vệ Sinh,"Bạn sẽ "" giải quyết nỗi buồn"" thế nào nếu khôn...",NXB Kim Đồng,22000,Đang,18500,11/07/2016,NXB Kim Đồng,0,200
4,4,Amanda Huynh,Lam,Nhân vật chính của các mẩu truyện hay tản văn ...,NXB Trẻ,85000,164,72000,14/07/2016,NXB Trẻ,0,300
...,...,...,...,...,...,...,...,...,...,...,...,...
1267,1267,Kudoh Noriko,Chiếp Chiếp Đi Công Viên Giải Trí,chiếp chiếp.,Nhã Nam,44000,32,37000,22/09/2017,NXB Thế Giới,0,200
1268,1268,Trường An,Hồ Dương - Tâp 1,"Trong những năm tháng đó, ai đúng ai sai khôn...",NXB Phụ Nữ,217000,728,184000,01/09/2017,NXB Phụ Nữ,0,950
1269,1269,Karen Dillon,HBR Guide To - Sống Sót Nơi Công Sở,• Chống lại những kẻ đâm sau lưng và ưa bắt nạt ;,Alphabooks,99000,228,84000,22/09/2017,NXB Thế Giới,0,370
1270,1270,Porter Erisman,Thế Giới Alibaba Của Jack Ma,Tác giả viết sách còn làm một bộ phim tài liệu...,NXB Trẻ,105000,322,89000,01/09/2017,NXB Trẻ,0,522
1271,1271,Lê Anh Vinh,Học Toán Qua Truyện Cổ Tích - Cây Khế,là sản phẩm nằm trong bộ sản phẩm Học toán qua...,Thái Hà,49000,34,41500,10/10/2017,NXB Thế Giới,0,184

In [10]:
df['Status'] .value_counts()

Status
0    1224
1      48
Name: count, dtype: int64

In [11]:
df.describe()

            index  Market_Price         Price       Status
count  1272.00000  1.272000e+03  1.272000e+03  1272.000000
mean    635.50000  9.153105e+04  7.754481e+04     0.037736
std     367.33908  9.135878e+04  7.768013e+04     0.190632
min       0.00000  1.000000e+04  7.500000e+03     0.000000
25%     317.75000  5.200000e+04  4.400000e+04     0.000000
50%     635.50000  7.900000e+04  6.700000e+04     0.000000
75%     953.25000  1.090000e+05  9.250000e+04     0.000000
max    1271.00000  2.000000e+06  1.700000e+06     1.000000